### ISSUE TITLE
Stop timeout when debugger is invoked

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-faulthandler#12]
When having a `import pdb; pdb.set_trace()` somewhere to debug something, the timeout still continues to run.

If pytest exposes hooks for that (I didn't check yet), I think the timeout should be stopped there.

**Comment by nicoddemus** [comment]
Thanks for the suggestion @The-Compiler! :smile:

There's a `pytest_enter_pdb` hook that is now properly documented in pytest-dev/pytest#1188.
