### ISSUE TITLE
Feature Request: Defining timeout via pytest.ini variable

### ISSUE THREAD

**Issue by 2xB** [pytest-dev/pytest-faulthandler#34]
Hey, thank you for this lightweight package! In the following, I'd like to suggest a small feature.

## Suggestion
Add a faulthandler-timeout variable to the pytest.ini parser.

## Explanation
Currently, it seems as if it is not possible to specify a faulthandler timeout in a pytest.ini file in a way that it also works without having pytest-faulthandler installed. With a custom variable, this should be trivial.

---

Note that something similar to this suggestion is already implemented by pytest-timeout, so that might give a good blueprint.

**Comment by nicoddemus** [comment]
Hi @2xB, thanks for writing.

I see you already seem to know about `addopts`, but can you describe the use case a little more so I can understand why you need the option without the plugin installed?

Btw, the plugin itself will be integrated into the core and will come out in pytest 5.0. 😁

**Comment by 2xB** [comment]
That is exciting!
Okay, here is the problem: When I specify `addopts = --faulthandler-timeout=15` in `pytest.ini` and run pytest without pytest-faulthandler, I get:
```
ERROR: usage: py.test [options] [file_or_dir] [file_or_dir] [...]
py.test: error: unrecognized arguments: --faulthandler-timeout=15
```
Therefore now pytest-faulthandler is a requirement for this `pytest.ini`, which I would like to avoid.

**Comment by nicoddemus** [comment]
Ahh OK. Another way to customize options is to use the `PYTEST_ADDOPTS` environment variable, which then wouldn't require changing the file in the repository.

**Comment by 2xB** [comment]
Thank you for your fast response! Yes. I saw that `pytest-timeout` provides such a parameter in `pytest.ini`, and therefore thought that having it as a parameter in `pytest.ini` would be the easiest solution there, since it would allow consistent results when using pytest-faulthandler.

**Comment by nicoddemus** [comment]
Thanks @2xB. I have implemented `faulthandler_timeout` as an ini option, while removing the `--faulthandler-timeout` command line option: having as an ini option still lets users set it from the command-line using `-o faulthandler_timeout`, so no functionality is lost.  

Thanks for the suggestion and discussion. 👍

**Comment by 2xB** [comment]
Thank you very much for the discussion and the incredibly quick implementation!

**Comment by j9ac9k** [comment]
@nicoddemus pardon me for replying to a closed issue but I just wanted to thank you for making this change, this is saving is a major head ache!

**Comment by nicoddemus** [comment]
> @nicoddemus pardon me for replying to a closed issue 

That's perfectly fine. 😁 

>  I just wanted to thank you for making this change, this is saving is a major head ache!

Sure, thanks for the report!
