### ISSUE TITLE
pytest --faulthandler-timeout does not work with pytest 5.0.0

### ISSUE THREAD

**Issue by pablogsal** [pytest-dev/pytest-faulthandler#35]
After `pytest-faulthandler` was integrated into the core of pytest 5.0.0 only the ini-option `faulthandler_timeout` is available, but this shadows the usage of `faulthandler-timeout`:

```
❯ python -m pytest --faulthandler_timeout=10
/Users/pgalindo3/.local/share/virtualenvs/venv-TdjqqweH/lib/python3.7/site-packages/_pytest/config/__init__.py:297: PytestConfigWarning: pytest-faulthandler plugin has been merged into the core, please remove it from your requirements.
  name.replace("_", "-")
ERROR: usage: pytest.py [options] [file_or_dir] [file_or_dir] [...]
pytest.py: error: unrecognized arguments: --faulthandler_timeout=10
  inifile: /Users/pgalindo/github/venv/tox.ini
  rootdir: /Users/pgalindo/github/venv
```

If this should be an issue on https://github.com/pytest-dev/pytest I can close this and reopen one ther e :)

**Comment by nicoddemus** [comment]
Can you please show the full output? You should have been seeing a warning about pytest-faulthandler being merged into the core...

**Comment by pablogsal** [comment]
I will paste here the output but in any case one of the problems is that is not possible to configure the option with a command line argument in pytest core now (only the ini file option is allowed).

**Comment by nicoddemus** [comment]
Oh I see. You can configure the ini option from the command-line using the `-o` option: 

```
$ pytest -o faulthandler_timeout=10
```

**Comment by nicoddemus** [comment]
Closing for now, feel free to follow up with further questions. 👍
