### ISSUE TITLE
Please release dummy 2.0 package

### ISSUE THREAD

**Issue by hmaarrfk** [pytest-dev/pytest-faulthandler#36]
Hi,

I think it would be cool if you could release a 2.0 package that is just a dummy package that simply depends on pytest>5.0.

This would help downstream transition to pytest 5.0 without explicitly depending on it.

Thanks!

Mark

https://github.com/scikit-image/scikit-image/issues/3986

**Comment by nicoddemus** [comment]
Hi @hmaarrfk,

I was thinking of doing that, but wasn't sure if it would help or not. But I guess it indeed it would be helpful. I will look into it. 👍

**Comment by hmaarrfk** [comment]
Cool awesome!

**Comment by nicoddemus** [comment]
Done, thanks for the suggestion!
