### ISSUE TITLE
Add support for dumping stack after a timeout

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-faulthandler#5]
I currently have a test which hangs on Windows sometimes, and I have no idea why - so I thought about adding something to pytest-faulthandler which essentially does this:
- Add an argument `--faulthandler-timeout 60` or so - the traceback will be dumped after that many seconds.
- Before each test, call `faulthandler.dump_traceback_later(timeout)`
- After each test, call `faulthandler.cancel_dump_traceback_later()`

What do you think?

**Comment by nicoddemus** [comment]
Nice, I like the idea! :sunglasses: 

I will work on it next week, should be simple enough to implement, thanks for the suggestion Florian!
