### ISSUE TITLE
Handling --faulthandler-timeout on a mixed OS CI

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-faulthandler#8]
I just wanted to add `--faulthandler-timeout 20` to my `tox.ini`, but that broke my tests on Windows as it's not supported there.

What's the best way to solve this? The two things I can think of is adding a `--faulthandler-maybe-timeout` or so which gets ignored on Windows (rather than being an error), or adding some hook to my `conftest.py` which adds the option if not on Windows (but `pytest_cmdline_preparse` which sounded appropriate is deprecated).

What do you think?

**Comment by The-Compiler** [comment]
@nicoddemus any idea what I could do about this? :smile:

**Comment by nicoddemus** [comment]
Sorry, I completely missed this message. :sweat_smile: 

I think we can instead of raising an error we just issue a pytest-warning... what do you think?

**Comment by The-Compiler** [comment]
I think that'd work for me - I don't like the idea of always getting a pytest-warning, but it's probably fine if that happens on the CI.
