### ISSUE TITLE
Expose faulthandler.register

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-faulthandler#9]
[faulthandler.register](https://docs.python.org/3.4/library/faulthandler.html#faulthandler.register) is quite useful (and also doesn't exist on Windows, unfortunately) - it allows a user to send a signal to the process to show the traceback.

I think it should be exposed by `pytest-faulthandler` as well, with a `--faulthandler-signal=SIGUSR1` argument (for example).

It then does `getattr(signal, faulthandler_signal)` and `getattr(signal, 'SIG' + faulthandler_signal)` (with `signal` being the signal module) to find out which signal the user meant. The second variant is useful as leaving off the `SIG` is an usual thing to do (e.g. when using `kill`, that works as well).

Then it calls `faulthandler.register` to register output to the duplicated stdout and `faulthandler.unregister` when cleaning up.

I can work on this at some point in the future, but if you feel like, please go ahead! :smile:

**Comment by nicoddemus** [comment]
Could you provide a more detailed use case? Seems somewhat low level to ask the user to register a signal and send one manually... Also, it seems registering/un-registering could be done easily and perhaps even more clearly by using an autouse fixture (although one can argue that handling the duplicated stdout is reason enough for native pytest-faulthandler support).

Perhaps it would be more useful to include a fixture which the user can just call to dump a traceback at some point during testing? For example:

``` python
def test_foo(fh_dump):
    # test test test
    fh_dump.dump_tracebacks()
```

`dump_tracebacks(signum=SIGUSR1, all_threads=True, chain=False)` would then `register` the signal, trigger it and immediately `unregister` it.

**Comment by The-Compiler** [comment]
> Could you provide a more detailed use case? Seems somewhat low level to ask the user to register a signal and send one manually...

My use case was that I saw a hang at some point, but didn't want to wait for the timeout (and didn't want to set the timeout too low because I'm running on the CI with the same settings, where something like 5s might be too low). But I agree it probably isn't worth the effort on a second thought, so I'm closing this.

> `dump_tracebacks(signum=SIGUSR1, all_threads=True, chain=False)` would then `register` the signal, trigger it and immediately `unregister` it.

No need to do that, there's `faulthandler.dump_traceback(file=sys.stderr, all_threads=True)` too. It's probably not very useful though, as you usually know what the stack is inside your test code :wink:

**Comment by nicoddemus** [comment]
>  But I agree it probably isn't worth the effort on a second thought, so I'm closing this.

OK, but thanks for the discussion anyway. :grin: 

> No need to do that, there's faulthandler.dump_traceback(file=sys.stderr, all_threads=True) too. It's probably not very useful though, as you usually know what the stack is inside your test code

I think it would be useful to dump tracebacks from other threads.
